### ISSUE TITLE
[classes] Getting `TypeError: meta is not a function` after upgrading to v3.5.0 from v3.4.2

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#285]
Hey!

The whole message:

```
(node:812700) UnhandledPromiseRejectionWarning: TypeError: meta is not a function
    at Object.instantiate (x/node_modules/@automapper/classes/src/lib/utils/instantiate.util.js:38:28)
    at Object.instantiate (x/node_modules/@automapper/classes/src/lib/classes.js:21:28)
    at Object.initializeMapping (x/node_modules/@automapper/classes/src/lib/classes.js:43:70)
    at Object.createMap (x/node_modules/@automapper/core/src/lib/create-mapper/create-mapper.js:24:36)
    at x/dist/src/my.profile.js:22:18
    at Object.addProfile (x/node_modules/@automapper/core/src/lib/create-mapper/create-mapper.js:30:13)
    at x/node_modules/@automapper/nestjs/src/lib/abstracts/automapper-profile.abstract.js:7:50
```

The line bellow triggers the error:

https://github.com/nartc/mapper/blob/8d10e0b974d007b356306b50c7727b36a4b7f08c/packages/classes/src/lib/utils/instantiate.util.ts#L56

This happen when some optional attribute (with some non-primitive type) is annotated with `@Automap()` like:

```ts
class A {} // there is a profile for this

class Foo { // and another for this.
  @AutoMap() 
  bar?: A

  // But this works as expected: ✅
  @AutoMap()
  baz: A | undefined

  // and this too ✅
  @AutoMap({ typeFn: () => A })
  qux?: A;
}
```

maybe this is related to the [strict mode limitation](https://automapperts.netlify.app/docs/plugins-system/classes-limitations/#strict-mode) but I'm not sure.

**Comment by nartc** [comment]
This is a regression with the latest change to `AutoMap` decorator. Metadata of a property shouldn't be saved if `typeFn` is null. Although in this case, I'm not sure why Reflection is unable to get the `design:type` of `bar` when `bar` is optional. 

That said, 3.5.1 should fix this by reverting AutoMap behavior to the previous version which **WON'T** save the metadata of `bar` if it cannot find the `typeFn` for `bar`.
