### ISSUE TITLE
after upgrade 8.3.4 ,Cannot find module '~/codedir/node_modules/@automapper/nestjs/index.cjs'

### ISSUE THREAD

**Issue by zieglar** [nartc/mapper#472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

after upgrade to 8.3.4, build project normal, but start project notify error :Cannot find module '~/codedir/node_modules/@automapper/nestjs/index.cjs'

try to downgrade to 8.3.3, is ok.

in 8.3.3, run `ls node_modules/@automapper/nestjs`, print `index.cjs  index.d.ts  index.esm.js  lib  package.json  README.md`

in 8.3.4, run `ls node_modules/@automapper/nestjs`, print `index.cjs.js  index.d.ts  index.esm.js  lib  package.json  README.md`

and when upgrade to 8.3.4, 
```
warning " > @automapper/classes@8.3.4" has incorrect peer dependency "@automapper/core@0.0.0".
warning " > @automapper/nestjs@8.3.4" has incorrect peer dependency "@automapper/core@0.0.0".
```

### Steps to reproduce

yarn add @automapper/classes@8.3.4 @automapper/nestjs@8.3.4 @automapper/core@8.3.4
yarn remove @automapper/classes @automapper/nestjs @automapper/core
yarn add @automapper/classes@8.3.3 @automapper/nestjs@8.3.3 @automapper/core@8.3.3

### Expected behavior

fix 8.3.4 error

### Minimum reproduction code

8.3.4

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.4

### Additional context

[System Information]
OS Version     : macOS Big Sur
NodeJS Version : v14.17.5
YARN Version    : 1.22.18

[Nest CLI]
Nest CLI Version : 8.2.5

[Nest Platform Information]
platform-socket.io version : 8.4.4
platform-fastify version   : 8.4.4
websockets version         : 8.4.4
schematics version         : 8.0.10
passport version           : 8.2.1
terminus version           : 8.0.6
swagger version            : 5.2.1
testing version            : 8.4.4
common version             : 8.4.4
config version             : 2.0.0
axios version              : 0.0.7
bull version               : 0.5.4
core version               : 8.4.4
jwt version                : 8.0.0
cli version                : 8.2.5

**Comment by nartc** [comment]
@zieglar sorry for the inconvenience. 8.3.5 has been released with the fix
